### ISSUE TITLE
any manual about this 

### ISSUE THREAD

**Issue by xz0405** [amohan95/quantity-tracker#1]
hello,man 
will this can be used to get the stock information of a product?

**Comment by neoadventist** [comment]
@xz0405 I don't know. But it looks like it would be pretty out of date since it was last updated three years ago!

**Comment by amohan95** [comment]
Hey @xz0405, this hasn't been maintained for a while so I'm not sure it will work anymore if it's using an outdated API. Also we ran into problems with API limiting, so even if it still does work it may not be able to get all the data necessary.

**Comment by xz0405** [comment]
yes, i find a new one on github to replace it,any way thanks
